project_name: "asl_classification"
seed: 42

data:
  root_dir: "data/ASL_Alphabet_Dataset/asl_alphabet_train"
  batch_size: 64
  num_workers: 4
  img_size: [200, 200]
  input_channels: 3
  num_classes: 29
  val_split: 0.1
  test_split: 0.1

model:
  lr: 0.001
  hidden_dim: 128

trainer:
  max_epochs: 3
  accelerator: "auto"
  devices: 1

logger:
  experiment_name: "asl_recognition_v1"
  tracking_uri: "http://127.0.0.1:5000"

inference:
  checkpoint_path: "models/checkpoints/baseline-epoch=02-val_acc=0.81.ckpt"
