defaults:
  - _self_
  - model: resnet
  - data: default

runtime: "onnx"
providers:
  - "CPUExecutionProvider"
checkpoint_path: "models/checkpoints/baseline_cnn-epoch=02-val_acc=0.75.ckpt"
onnx_path: "models/model.onnx"
class_names: ${data.class_names}
img_size: ${data.img_size}
confidence_threshold: 0.3
input:
  image_path: null
